version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  assignees:
  - sue445
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: nio4r
    versions:
    - 2.5.4
    - 2.5.5
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: icalendar
    versions:
    - 2.7.0
